version: '3'

services:
  qemu:
    build: .
    working_dir: /root/project
    volumes:
      - .:/root/project
    command: |
      sh -c "PATH=$$PATH:$$HOME/.cargo/bin make && qemu-system-arm -M raspi2 -kernel build/arm/kernel.elf -vnc :0 -serial stdio"
